Mozilla/5.0 (Linux; U; Android 10; en-US; V2029 Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.4.0.1306 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; $os_version$; en-US; $devicename$) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.12.9.7.11578 UCBrowser/$version_uc_platform$ Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 12; en-US; SM-A515F Build/SP1A.210812.016) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.4.0.1306 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 12; en-US; SM-N986B Build/SP1A.210812.016) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.4.0.1306 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 11; en-US; M2003J15SC Build/RP1A.200720.011) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.4.0.1306 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 11; en-US; M2003J15SC Build/RP1A.200720.011) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.4.0.1306 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 10; en-US; RMX1821 Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.3.2.1303 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 11; en-US; SM-A325F Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.4.0.1306 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 11; en-US; V2026 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.4.0.1306 Mobile Safari/537.36
